CREATE TABLE Employees (
  EmployeeID INT NOT NULL IDENTITY(1,1),
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  PhoneNo VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  City VARCHAR(255) NOT NULL,
  State VARCHAR(255) NOT NULL,
  ZipCode VARCHAR(255) NOT NULL,
  Department VARCHAR(255) NOT NULL,
  Title VARCHAR(255) NOT NULL,
  HireDate DATE NOT NULL,
  Salary DECIMAL(10,2) NOT NULL,
  Notes VARCHAR(255) NOT NULL
);

